import sqlite3

# Δημιουργία σύνδεσης με τη βάση δεδομένων
conn = sqlite3.connect('email_database.db')
cursor = conn.cursor()

# Δημιουργία του πίνακα email_list
cursor.execute('''
CREATE TABLE IF NOT EXISTS email_list (
    id INTEGER PRIMARY KEY,
    email TEXT NOT NULL UNIQUE
)
''')

# Νέα λίστα με πραγματικά email
real_data = [
    ('mvrek@chemistry.uch.gr',),
    ('office@chiosonline.gr',),
    ('nl@choosead.gr',),
    ('nl@choosemedia.gr',),
    ('stergios@city.academic.gr',),
    ('info@codepoetry.gr',),
    ('nikos@comparison.gr',),
    ('mstamiri@compulink.gr',),
    ('ostria@compulink.gr',),
    ('manager@crcgroup.gr',),
    ('chris@cretaforce.gr',),
    ('partners@cybertools.gr',),
    ('pmouzouri@cyta.gr',),
    ('info@dat.net.gr',),
    ('nmoniodis@datapower.gr',),
    ('dimitra@deca.gr',),
    ('ailiakis@designgraphic.gr',),
    ('info@diadyo.gr',),
    ('np@din.gr',),
    ('koumoutzi.a@dsa.gr',),
    ('info@e-vitrine.gr',),
    ('nikosf@ebox.gr',),
    ('sales@edemvacations.gr',),
    ('melkor@edu.biology.uoc.gr',),
    ('stefanos@ees.gr',),
    ('persefon@eexi.gr',),
    ('info@ekon.gr',),
    ('eirini@elargo.gr',),
    ('info@emagine.gr',),
    ('dracos@eneiset.gr',),
    ('info@enerdomi.gr',),
    ('mchazakis@eopyy.gov.gr',),
    ('nick.zafiris@epicon.gr',),
    ('milis@epsa.gr',),
    ('militsim@ethnodata.gr',),
    ('nkorop@eyempoiein.gr',),
    ('nkostis@fhw.gr',),
    ('fire@fire.gr',),
    ('abuse@forthnet.gr',),
    ('maria-@freemail.electrobbs.gr',),
    ('megalos@freemail.gr',),
    ('meltinis@freemail.gr',),
    ('mitsos@freemail.gr',),
    ('mitsosg13@freemail.gr',),
    ('mrzammler@freemail.gr',),
    ('nkatsar@freemail.gr',),
    ('nkoukos@freemail.gr',),
    ('ntg9@freemail.gr',),
    ('on@freemail.gr',),
    ('pantelhs@freemail.gr',),
    ('pantelisv@freemail.gr',),
    ('paterakisg@freemail.gr',),
    ('pgkioul@freemail.gr',),
    ('piatrou@freemail.gr',),
    ('galaxias@galaxias.net.gr',),
    ('info@gallerytounotou.gr',),
    ('id@georgeg.gr',),
    ('info@getonweb.gr',),
    ('info@glasstech.gr',),
    ('web@global-tech.gr',),
    ('info@glsstech.gr',),
    ('webmaster@go-thassos.gr',),
    ('nigelhcopage@goodtimes.gr',),
    ('zoran@goto.gr',),
    ('nickosp@groovy.gr',),
    ('margtsou@hellasnet.gr',),
    ('microchip@hellasnet.gr',),
    ('order@help-hosting.gr',),
    ('paris22@hlk.forthnet.gr',),
    ('1theogero@hol.gr',),
    ('cybermaster@hol.gr',),
    ('elkar@hol.gr',),
    ('jnezis@hol.gr',),
    ('klazar@hol.gr',),
    ('llurk@hol.gr',),
    ('makrisa@hol.gr',),
    ('marana@hol.gr',),
    ('markoman@hol.gr',),
    ('mediadyne@hol.gr',),
    ('mpp113@hol.gr',),
    ('nautilus@hol.gr',),
    ('nefstath@hol.gr',),
    ('nino@hol.gr',),
    ('paloulis@hol.gr',),
    ('pansoft@hol.gr',),
    ('paris@hol.gr',),
    ('pekasi@hol.gr',),
    ('pirate@hol.gr',),
    ('planodtp@hol.gr',),
    ('sakelar@hol.gr',),
    ('sdorothea@hol.gr',),
    ('sotfam@hol.gr',),
    ('tsitidou@hol.gr',),
    ('a.mourgelas@hotmail.gr',),
    ('andreas.1993@hotmail.gr',),
    ('arben2010@hotmail.gr',),
    ('arva2004m@hotmail.gr',),
    ('eristar100@hotmail.gr',),
    ('gianisforever@hotmail.gr',),
    ('johnfallon@hotmail.gr',),
    ('lavdanitis@hotmail.gr',),
    ('maral95@hotmail.gr',),
    ('mrpaulos79@hotmail.gr',),
    ('nicholas_markopoulos@hotmail.gr',),
    ('npleo69@hotmail.gr',),
    ('vaggelisaggelidakis@hotmail.gr',),
    ('maverick@humanworks.gr',),
    ('webadmin@i4g.gr',),
    ('pbratsos@ifet.gr',),
    ('ziakis@imarketing.gr',),
    ('chrisba@in.gr',),
    ('chrislancia@in.gr',),
    ('egeit@in.gr',),
    ('kostasmaria@in.gr',),
    ('lupusg@in.gr',),
    ('mariakos@in.gr',),
    ('pontipa1@in.gr',),
    ('wasstek@in.gr',),
    ('cy@infinity.gr',),
    ('pkatsanos@infodyn.gr',),
    ('info@inspiration.gr',),
    ('mafrag@internet.gr',),
    ('p.a.s@internet.gr',),
    ('info@interten.gr',),
    ('dexar@ioniosbrokers.gr',),
    ('nsideras@it-w.gr',),
    ('info@johnpapast.gr',),
    ('admin@kepos.gr',),
    ('neted@kerveros.gr',),
    ('pan@kos.forthnet.gr',),
    ('info@ladasfoods.gr',),
    ('tonys@land4all.gr',),
    ('info@ldal.gr',),
    ('sales@linkshop.gr',),
    ('n.kofinas@lithografiki.com.gr',),
    ('acme_art@mail.gr',),
    ('antonia76@mail.gr',),
    ('lyklam3@mail.gr',),
    ('melodyilias@mail.gr',),
    ('mikee@mail.gr',),
    ('nigrita@mail.gr',),
    ('pgge3@mail.gr',),
    ('pikatsulas_7@mail.gr',),
    ('nks21r@mailbox.gr',),
    ('nt1@mailbox.gr',),
    ('orfanos@mailbox.gr',),
    ('info@mediavoice.gr',),
    ('methos@methos.gr',),
    ('stathis.tsiriopoulos@minisys.gr',),
    ('nant@mland.gr',),
    ('mmingos@mls.gr',),
    ('modeling@modeling.gr',),
    ('akartalis@moraitis.edu.gr',),
    ('info@motronix.gr',),
    ('motronix@motronix.gr',),
    ('spaschalis@mspaschalis.gr',),
    ('manager@multiprint.gr',),
    ('musicdance@music-dance.gr',),
    ('djmonitor@mycosmos.gr',),
    ('limitup@mycosmos.gr',),
    ('meletis@mycosmos.gr',),
    ('info@myepage.gr',),
    ('john@nbd.gr',),
    ('kilarou.maria@nbg.gr',),
    ('nick@net-club.gr',),
    ('info@netikon.gr',),
    ('chatziapostolou@netlamb.gr',),
    ('info@netme.gr',),
    ('nick@networkdynamics.gr',),
    ('manos@niotakis.gr',),
    ('dps@novacl.gr',),
    ('msinas@on.gr',),
    ('nsi@origin.gr',),
    ('39strato@otenet.gr',),
    ('ambroh@otenet.gr',),
    ('aneroy70@otenet.gr',),
    ('aris2006@otenet.gr',),
    ('cavomit@otenet.gr',),
    ('cdermen@otenet.gr',),
    ('constarv@otenet.gr',),
    ('ctsiatsos@otenet.gr',),
    ('dimos32@otenet.gr',),
    ('dkristal@otenet.gr',),
    ('eli3@otenet.gr',),
    ('ezia91@otenet.gr',),
    ('gath55@otenet.gr',),
    ('gradwyer@otenet.gr',),
    ('heart939@otenet.gr',),
    ('iliomd@otenet.gr',),
    ('ioannoub@otenet.gr',),
    ('kagianni@otenet.gr',),
    ('ksw@otenet.gr',),
    ('liourika@otenet.gr',),
    ('lyhnari@otenet.gr',),
    ('magda_kyr@otenet.gr',),
    ('magicarp@otenet.gr',),
    ('makrin@otenet.gr',),
    ('mal-ser@otenet.gr',),
    ('malindop@otenet.gr',),
    ('mandreka@otenet.gr',),
]

# Εισαγωγή των νέων δεδομένων
for email in real_data:
    try:
        cursor.execute('INSERT INTO email_list (email) VALUES (?)', email)
    except sqlite3.IntegrityError:
        print(f"Duplicate email found: {email[0]}. Skipping.")

# Αποθήκευση των αλλαγών και κλείσιμο της σύνδεσης
conn.commit()
conn.close()
print("Η βάση δεδομένων ενημερώθηκε με τις πραγματικές διευθύνσεις email.")

